server:
  port: 8888

spring:
  redis:
    host: 192.168.4.131
    port: 6379
    password: WzQ9oWgx
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

